// Renders the "Latest articles" sections from data/latest.json,
// which is regenerated by scripts/fetch_rss.py (run by GitHub Actions).
// The list is split: the 5 newest go in #latest-articles-top, the rest in
// #latest-articles-rest. On phones a "Read more" button reveals the Selected
// work section between the two groups.

(function () {
  var top = document.getElementById('latest-articles-top');
  var rest = document.getElementById('latest-articles-rest');
  var legacy = document.getElementById('latest-articles');
  var btn = document.getElementById('read-more');

  function esc(s) {
    return String(s || '').replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function render(items, container) {
    // Latest shows headline + picture only (no date, no description).
    container.innerHTML = items.map(function (it) {
      var img = it.image
        ? '<a class="thumb" href="' + esc(it.link) + '"><img src="' + esc(it.image) + '" alt="" loading="lazy"></a>'
        : '';
      return '<article>' + img +
        '<h3><a href="' + esc(it.link) + '">' + esc(it.title) + '</a></h3>' +
        '</article>';
    }).join('');
  }

  function empty(msg) {
    var html = '<p><em>' + msg + '</em></p>';
    if (top) top.innerHTML = html;
    else if (legacy) legacy.innerHTML = html;
  }

  fetch('data/latest.json')
    .then(function (r) { if (!r.ok) throw new Error('fetch failed'); return r.json(); })
    .then(function (items) {
      if (!items.length) {
        empty('No recent articles found.');
        return;
      }
      if (top && rest) {
        render(items.slice(0, 5), top);
        render(items.slice(5), rest);
      } else if (legacy) {
        render(items, legacy); // older page markup: everything in one list
      }
    })
    .catch(function () {
      empty('Could not load the latest articles.');
    });

  // Phone-only button: unfurls the Selected work section between the two
  // latest groups. (The button is hidden on desktop via CSS.)
  if (btn) {
    btn.addEventListener('click', function () {
      // Toggle on both body and .columns so the button keeps working even
      // if the stylesheet and script versions are briefly out of sync.
      var expanded = document.body.classList.toggle('expanded');
      var cols = btn.closest('.columns');
      if (cols) cols.classList.toggle('expanded', expanded);
      btn.setAttribute('aria-expanded', expanded ? 'true' : 'false');
      btn.textContent = expanded ? 'Read less' : 'Read more';
    });
  }
})();
