// Renders the "Latest articles" section from data/latest.json,
// which is regenerated by scripts/fetch_rss.py (run by GitHub Actions).

(function () {
  var container = document.getElementById('latest-articles');
  if (!container) return;

  function esc(s) {
    return String(s || '').replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function shortDate(pubDate) {
    // "Thu, 01 Oct 2026 11:12:00 -0500" -> "Oct 1, 2026"
    var m = /^(\w+), (\d+) (\w+) (\d+)/.exec(pubDate || '');
    if (!m) return '';
    return m[3] + ' ' + parseInt(m[2], 10) + ', ' + m[4];
  }

  fetch('data/latest.json')
    .then(function (r) { if (!r.ok) throw new Error('fetch failed'); return r.json(); })
    .then(function (items) {
      if (!items.length) {
        container.innerHTML = '<p><em>No recent articles found.</em></p>';
        return;
      }
      container.innerHTML = items.map(function (it) {
        // Right column shows headline + picture only (no date, no description).
        var img = it.image
          ? '<a class="thumb" href="' + esc(it.link) + '"><img src="' + esc(it.image) + '" alt="" loading="lazy"></a>'
          : '';
        return '<article>' + img +
          '<h3><a href="' + esc(it.link) + '">' + esc(it.title) + '</a></h3>' +
          '</article>';
      }).join('');
    })
    .catch(function () {
      container.innerHTML = '<p><em>Could not load the latest articles.</em></p>';
    });
})();
